//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Activity.
    /// </summary>
    // *** Start programmer edit section *** (Activity CustomAttributes)

    // *** End programmer edit section *** (Activity CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ActivityE", new string[] {
            "ActivityName as \'Activity name\'",
            "ActivityType as \'Activity type\'",
            "StartOfActivity as \'Start of activity\'",
            "EndOfActivity as \'End of activity\'",
            "Contact as \'Contact\'",
            "Contact.Name as \'Name\'",
            "Lead as \'Lead\'",
            "Lead.Name as \'Name\'"}, Hidden=new string[] {
            "Contact.Name",
            "Lead.Name"})]
    [MasterViewDefineAttribute("ActivityE", "Contact", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("ActivityE", "Lead", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("ActivityL", new string[] {
            "ActivityName as \'Activity name\'",
            "ActivityType as \'Activity type\'",
            "StartOfActivity as \'Start of activity\'",
            "EndOfActivity as \'End of activity\'",
            "Contact.Name as \'Name\'",
            "Lead.Name as \'Name\'"})]
    public class Activity : ICSSoft.STORMNET.DataObject
    {
        
        private string fActivityName;
        
        private IIS.CRM.tActivity fActivityType;
        
        private System.DateTime fStartOfActivity;
        
        private System.DateTime fEndOfActivity;
        
        private IIS.CRM.Contact fContact;
        
        private IIS.CRM.Lead fLead;
        
        // *** Start programmer edit section *** (Activity CustomMembers)

        // *** End programmer edit section *** (Activity CustomMembers)

        
        /// <summary>
        /// ActivityName.
        /// </summary>
        // *** Start programmer edit section *** (Activity.ActivityName CustomAttributes)

        // *** End programmer edit section *** (Activity.ActivityName CustomAttributes)
        [StrLen(255)]
        public virtual string ActivityName
        {
            get
            {
                // *** Start programmer edit section *** (Activity.ActivityName Get start)

                // *** End programmer edit section *** (Activity.ActivityName Get start)
                string result = this.fActivityName;
                // *** Start programmer edit section *** (Activity.ActivityName Get end)

                // *** End programmer edit section *** (Activity.ActivityName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.ActivityName Set start)

                // *** End programmer edit section *** (Activity.ActivityName Set start)
                this.fActivityName = value;
                // *** Start programmer edit section *** (Activity.ActivityName Set end)

                // *** End programmer edit section *** (Activity.ActivityName Set end)
            }
        }
        
        /// <summary>
        /// ActivityType.
        /// </summary>
        // *** Start programmer edit section *** (Activity.ActivityType CustomAttributes)

        // *** End programmer edit section *** (Activity.ActivityType CustomAttributes)
        public virtual IIS.CRM.tActivity ActivityType
        {
            get
            {
                // *** Start programmer edit section *** (Activity.ActivityType Get start)

                // *** End programmer edit section *** (Activity.ActivityType Get start)
                IIS.CRM.tActivity result = this.fActivityType;
                // *** Start programmer edit section *** (Activity.ActivityType Get end)

                // *** End programmer edit section *** (Activity.ActivityType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.ActivityType Set start)

                // *** End programmer edit section *** (Activity.ActivityType Set start)
                this.fActivityType = value;
                // *** Start programmer edit section *** (Activity.ActivityType Set end)

                // *** End programmer edit section *** (Activity.ActivityType Set end)
            }
        }
        
        /// <summary>
        /// StartOfActivity.
        /// </summary>
        // *** Start programmer edit section *** (Activity.StartOfActivity CustomAttributes)

        // *** End programmer edit section *** (Activity.StartOfActivity CustomAttributes)
        public virtual System.DateTime StartOfActivity
        {
            get
            {
                // *** Start programmer edit section *** (Activity.StartOfActivity Get start)

                // *** End programmer edit section *** (Activity.StartOfActivity Get start)
                System.DateTime result = this.fStartOfActivity;
                // *** Start programmer edit section *** (Activity.StartOfActivity Get end)

                // *** End programmer edit section *** (Activity.StartOfActivity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.StartOfActivity Set start)

                // *** End programmer edit section *** (Activity.StartOfActivity Set start)
                this.fStartOfActivity = value;
                // *** Start programmer edit section *** (Activity.StartOfActivity Set end)

                // *** End programmer edit section *** (Activity.StartOfActivity Set end)
            }
        }
        
        /// <summary>
        /// EndOfActivity.
        /// </summary>
        // *** Start programmer edit section *** (Activity.EndOfActivity CustomAttributes)

        // *** End programmer edit section *** (Activity.EndOfActivity CustomAttributes)
        public virtual System.DateTime EndOfActivity
        {
            get
            {
                // *** Start programmer edit section *** (Activity.EndOfActivity Get start)

                // *** End programmer edit section *** (Activity.EndOfActivity Get start)
                System.DateTime result = this.fEndOfActivity;
                // *** Start programmer edit section *** (Activity.EndOfActivity Get end)

                // *** End programmer edit section *** (Activity.EndOfActivity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.EndOfActivity Set start)

                // *** End programmer edit section *** (Activity.EndOfActivity Set start)
                this.fEndOfActivity = value;
                // *** Start programmer edit section *** (Activity.EndOfActivity Set end)

                // *** End programmer edit section *** (Activity.EndOfActivity Set end)
            }
        }
        
        /// <summary>
        /// Activity.
        /// </summary>
        // *** Start programmer edit section *** (Activity.Contact CustomAttributes)

        // *** End programmer edit section *** (Activity.Contact CustomAttributes)
        [NotNull()]
        public virtual IIS.CRM.Contact Contact
        {
            get
            {
                // *** Start programmer edit section *** (Activity.Contact Get start)

                // *** End programmer edit section *** (Activity.Contact Get start)
                IIS.CRM.Contact result = this.fContact;
                // *** Start programmer edit section *** (Activity.Contact Get end)

                // *** End programmer edit section *** (Activity.Contact Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.Contact Set start)

                // *** End programmer edit section *** (Activity.Contact Set start)
                this.fContact = value;
                // *** Start programmer edit section *** (Activity.Contact Set end)

                // *** End programmer edit section *** (Activity.Contact Set end)
            }
        }
        
        /// <summary>
        /// Activity.
        /// </summary>
        // *** Start programmer edit section *** (Activity.Lead CustomAttributes)

        // *** End programmer edit section *** (Activity.Lead CustomAttributes)
        [NotNull()]
        public virtual IIS.CRM.Lead Lead
        {
            get
            {
                // *** Start programmer edit section *** (Activity.Lead Get start)

                // *** End programmer edit section *** (Activity.Lead Get start)
                IIS.CRM.Lead result = this.fLead;
                // *** Start programmer edit section *** (Activity.Lead Get end)

                // *** End programmer edit section *** (Activity.Lead Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.Lead Set start)

                // *** End programmer edit section *** (Activity.Lead Set start)
                this.fLead = value;
                // *** Start programmer edit section *** (Activity.Lead Set end)

                // *** End programmer edit section *** (Activity.Lead Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ActivityE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ActivityE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ActivityE", typeof(IIS.CRM.Activity));
                }
            }
            
            /// <summary>
            /// "ActivityL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ActivityL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ActivityL", typeof(IIS.CRM.Activity));
                }
            }
        }
    }
}
