//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Administrator.
    /// </summary>
    // *** Start programmer edit section *** (Administrator CustomAttributes)

    // *** End programmer edit section *** (Administrator CustomAttributes)
    [AutoAltered()]
    [Caption("Admin")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AdministratorE", new string[] {
            "Name as \'Name\'",
            "Role as \'Role\'"})]
    [View("AdministratorL", new string[] {
            "Name as \'Name\'",
            "Role as \'Role\'"})]
    public class Administrator : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fRole;
        
        // *** Start programmer edit section *** (Administrator CustomMembers)

        // *** End programmer edit section *** (Administrator CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Administrator.Name CustomAttributes)

        // *** End programmer edit section *** (Administrator.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Administrator.Name Get start)

                // *** End programmer edit section *** (Administrator.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Administrator.Name Get end)

                // *** End programmer edit section *** (Administrator.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Administrator.Name Set start)

                // *** End programmer edit section *** (Administrator.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Administrator.Name Set end)

                // *** End programmer edit section *** (Administrator.Name Set end)
            }
        }
        
        /// <summary>
        /// Role.
        /// </summary>
        // *** Start programmer edit section *** (Administrator.Role CustomAttributes)

        // *** End programmer edit section *** (Administrator.Role CustomAttributes)
        [StrLen(255)]
        public virtual string Role
        {
            get
            {
                // *** Start programmer edit section *** (Administrator.Role Get start)

                // *** End programmer edit section *** (Administrator.Role Get start)
                string result = this.fRole;
                // *** Start programmer edit section *** (Administrator.Role Get end)

                // *** End programmer edit section *** (Administrator.Role Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Administrator.Role Set start)

                // *** End programmer edit section *** (Administrator.Role Set start)
                this.fRole = value;
                // *** Start programmer edit section *** (Administrator.Role Set end)

                // *** End programmer edit section *** (Administrator.Role Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AdministratorE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AdministratorE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AdministratorE", typeof(IIS.CRM.Administrator));
                }
            }
            
            /// <summary>
            /// "AdministratorL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AdministratorL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AdministratorL", typeof(IIS.CRM.Administrator));
                }
            }
        }
    }
}
