//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contact.
    /// </summary>
    // *** Start programmer edit section *** (Contact CustomAttributes)

    // *** End programmer edit section *** (Contact CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ContactE", new string[] {
            "Telephone as \'Telephone\'",
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Address as \'Address\'",
            "CompanyName as \'Company name\'",
            "Gender as \'Gender\'",
            "Email as \'Email\'",
            "Role as \'Role\'",
            "Date as \'Date\'",
            "Administrator as \'Administrator\'",
            "Administrator.Name as \'Name\'"}, Hidden=new string[] {
            "Administrator.Name"})]
    [MasterViewDefineAttribute("ContactE", "Administrator", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("ContactL", new string[] {
            "Telephone as \'Telephone\'",
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Address as \'Address\'",
            "CompanyName as \'Company name\'",
            "Gender as \'Gender\'",
            "Email as \'Email\'",
            "Role as \'Role\'",
            "Date as \'Date\'",
            "Administrator.Name as \'Name\'"})]
    public class Contact : ICSSoft.STORMNET.DataObject
    {
        
        private int fTelephone;
        
        private string fName;
        
        private string fSurname;
        
        private string fAddress;
        
        private string fCompanyName;
        
        private IIS.CRM.tGender fGender;
        
        private string fEmail;
        
        private string fRole;
        
        private System.DateTime fDate;
        
        private IIS.CRM.Administrator fAdministrator;
        
        // *** Start programmer edit section *** (Contact CustomMembers)

        // *** End programmer edit section *** (Contact CustomMembers)

        
        /// <summary>
        /// Telephone.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Telephone CustomAttributes)

        // *** End programmer edit section *** (Contact.Telephone CustomAttributes)
        public virtual int Telephone
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Telephone Get start)

                // *** End programmer edit section *** (Contact.Telephone Get start)
                int result = this.fTelephone;
                // *** Start programmer edit section *** (Contact.Telephone Get end)

                // *** End programmer edit section *** (Contact.Telephone Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Telephone Set start)

                // *** End programmer edit section *** (Contact.Telephone Set start)
                this.fTelephone = value;
                // *** Start programmer edit section *** (Contact.Telephone Set end)

                // *** End programmer edit section *** (Contact.Telephone Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Name CustomAttributes)

        // *** End programmer edit section *** (Contact.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Name Get start)

                // *** End programmer edit section *** (Contact.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Contact.Name Get end)

                // *** End programmer edit section *** (Contact.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Name Set start)

                // *** End programmer edit section *** (Contact.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Contact.Name Set end)

                // *** End programmer edit section *** (Contact.Name Set end)
            }
        }
        
        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Surname CustomAttributes)

        // *** End programmer edit section *** (Contact.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Surname Get start)

                // *** End programmer edit section *** (Contact.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Contact.Surname Get end)

                // *** End programmer edit section *** (Contact.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Surname Set start)

                // *** End programmer edit section *** (Contact.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Contact.Surname Set end)

                // *** End programmer edit section *** (Contact.Surname Set end)
            }
        }
        
        /// <summary>
        /// Address.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Address CustomAttributes)

        // *** End programmer edit section *** (Contact.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Address Get start)

                // *** End programmer edit section *** (Contact.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (Contact.Address Get end)

                // *** End programmer edit section *** (Contact.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Address Set start)

                // *** End programmer edit section *** (Contact.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Contact.Address Set end)

                // *** End programmer edit section *** (Contact.Address Set end)
            }
        }
        
        /// <summary>
        /// CompanyName.
        /// </summary>
        // *** Start programmer edit section *** (Contact.CompanyName CustomAttributes)

        // *** End programmer edit section *** (Contact.CompanyName CustomAttributes)
        [StrLen(255)]
        public virtual string CompanyName
        {
            get
            {
                // *** Start programmer edit section *** (Contact.CompanyName Get start)

                // *** End programmer edit section *** (Contact.CompanyName Get start)
                string result = this.fCompanyName;
                // *** Start programmer edit section *** (Contact.CompanyName Get end)

                // *** End programmer edit section *** (Contact.CompanyName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.CompanyName Set start)

                // *** End programmer edit section *** (Contact.CompanyName Set start)
                this.fCompanyName = value;
                // *** Start programmer edit section *** (Contact.CompanyName Set end)

                // *** End programmer edit section *** (Contact.CompanyName Set end)
            }
        }
        
        /// <summary>
        /// Gender.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Gender CustomAttributes)

        // *** End programmer edit section *** (Contact.Gender CustomAttributes)
        public virtual IIS.CRM.tGender Gender
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Gender Get start)

                // *** End programmer edit section *** (Contact.Gender Get start)
                IIS.CRM.tGender result = this.fGender;
                // *** Start programmer edit section *** (Contact.Gender Get end)

                // *** End programmer edit section *** (Contact.Gender Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Gender Set start)

                // *** End programmer edit section *** (Contact.Gender Set start)
                this.fGender = value;
                // *** Start programmer edit section *** (Contact.Gender Set end)

                // *** End programmer edit section *** (Contact.Gender Set end)
            }
        }
        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Email CustomAttributes)

        // *** End programmer edit section *** (Contact.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Email Get start)

                // *** End programmer edit section *** (Contact.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Contact.Email Get end)

                // *** End programmer edit section *** (Contact.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Email Set start)

                // *** End programmer edit section *** (Contact.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Contact.Email Set end)

                // *** End programmer edit section *** (Contact.Email Set end)
            }
        }
        
        /// <summary>
        /// Role.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Role CustomAttributes)

        // *** End programmer edit section *** (Contact.Role CustomAttributes)
        [StrLen(255)]
        public virtual string Role
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Role Get start)

                // *** End programmer edit section *** (Contact.Role Get start)
                string result = this.fRole;
                // *** Start programmer edit section *** (Contact.Role Get end)

                // *** End programmer edit section *** (Contact.Role Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Role Set start)

                // *** End programmer edit section *** (Contact.Role Set start)
                this.fRole = value;
                // *** Start programmer edit section *** (Contact.Role Set end)

                // *** End programmer edit section *** (Contact.Role Set end)
            }
        }
        
        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Date CustomAttributes)

        // *** End programmer edit section *** (Contact.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Date Get start)

                // *** End programmer edit section *** (Contact.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (Contact.Date Get end)

                // *** End programmer edit section *** (Contact.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Date Set start)

                // *** End programmer edit section *** (Contact.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (Contact.Date Set end)

                // *** End programmer edit section *** (Contact.Date Set end)
            }
        }
        
        /// <summary>
        /// Contact.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Administrator CustomAttributes)

        // *** End programmer edit section *** (Contact.Administrator CustomAttributes)
        [NotNull()]
        public virtual IIS.CRM.Administrator Administrator
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Administrator Get start)

                // *** End programmer edit section *** (Contact.Administrator Get start)
                IIS.CRM.Administrator result = this.fAdministrator;
                // *** Start programmer edit section *** (Contact.Administrator Get end)

                // *** End programmer edit section *** (Contact.Administrator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Administrator Set start)

                // *** End programmer edit section *** (Contact.Administrator Set start)
                this.fAdministrator = value;
                // *** Start programmer edit section *** (Contact.Administrator Set end)

                // *** End programmer edit section *** (Contact.Administrator Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ContactE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactE", typeof(IIS.CRM.Contact));
                }
            }
            
            /// <summary>
            /// "ContactL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactL", typeof(IIS.CRM.Contact));
                }
            }
        }
    }
}
