//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Employer.
    /// </summary>
    // *** Start programmer edit section *** (Employer CustomAttributes)

    // *** End programmer edit section *** (Employer CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EmployerE", new string[] {
            "Name as \'Name\'",
            "EmployerRole as \'Employer role\'",
            "Administrator as \'Administrator\'",
            "Administrator.Name as \'Name\'"}, Hidden=new string[] {
            "Administrator.Name"})]
    [MasterViewDefineAttribute("EmployerE", "Administrator", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("EmployerL", new string[] {
            "Name as \'Name\'",
            "EmployerRole as \'Employer role\'",
            "Administrator.Name as \'Name\'"})]
    public class Employer : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fEmployerRole;
        
        private IIS.CRM.Administrator fAdministrator;
        
        // *** Start programmer edit section *** (Employer CustomMembers)

        // *** End programmer edit section *** (Employer CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Employer.Name CustomAttributes)

        // *** End programmer edit section *** (Employer.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Employer.Name Get start)

                // *** End programmer edit section *** (Employer.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Employer.Name Get end)

                // *** End programmer edit section *** (Employer.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employer.Name Set start)

                // *** End programmer edit section *** (Employer.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Employer.Name Set end)

                // *** End programmer edit section *** (Employer.Name Set end)
            }
        }
        
        /// <summary>
        /// EmployerRole.
        /// </summary>
        // *** Start programmer edit section *** (Employer.EmployerRole CustomAttributes)

        // *** End programmer edit section *** (Employer.EmployerRole CustomAttributes)
        [StrLen(255)]
        public virtual string EmployerRole
        {
            get
            {
                // *** Start programmer edit section *** (Employer.EmployerRole Get start)

                // *** End programmer edit section *** (Employer.EmployerRole Get start)
                string result = this.fEmployerRole;
                // *** Start programmer edit section *** (Employer.EmployerRole Get end)

                // *** End programmer edit section *** (Employer.EmployerRole Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employer.EmployerRole Set start)

                // *** End programmer edit section *** (Employer.EmployerRole Set start)
                this.fEmployerRole = value;
                // *** Start programmer edit section *** (Employer.EmployerRole Set end)

                // *** End programmer edit section *** (Employer.EmployerRole Set end)
            }
        }
        
        /// <summary>
        /// Employer.
        /// </summary>
        // *** Start programmer edit section *** (Employer.Administrator CustomAttributes)

        // *** End programmer edit section *** (Employer.Administrator CustomAttributes)
        [NotNull()]
        public virtual IIS.CRM.Administrator Administrator
        {
            get
            {
                // *** Start programmer edit section *** (Employer.Administrator Get start)

                // *** End programmer edit section *** (Employer.Administrator Get start)
                IIS.CRM.Administrator result = this.fAdministrator;
                // *** Start programmer edit section *** (Employer.Administrator Get end)

                // *** End programmer edit section *** (Employer.Administrator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employer.Administrator Set start)

                // *** End programmer edit section *** (Employer.Administrator Set start)
                this.fAdministrator = value;
                // *** Start programmer edit section *** (Employer.Administrator Set end)

                // *** End programmer edit section *** (Employer.Administrator Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EmployerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployerE", typeof(IIS.CRM.Employer));
                }
            }
            
            /// <summary>
            /// "EmployerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployerL", typeof(IIS.CRM.Employer));
                }
            }
        }
    }
}
