//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Lead.
    /// </summary>
    // *** Start programmer edit section *** (Lead CustomAttributes)

    // *** End programmer edit section *** (Lead CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LeadE", new string[] {
            "Name as \'Name\'"})]
    [View("LeadL", new string[] {
            "Name as \'Name\'"})]
    public class Lead : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Lead CustomMembers)

        // *** End programmer edit section *** (Lead CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Lead.Name CustomAttributes)

        // *** End programmer edit section *** (Lead.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Lead.Name Get start)

                // *** End programmer edit section *** (Lead.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Lead.Name Get end)

                // *** End programmer edit section *** (Lead.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lead.Name Set start)

                // *** End programmer edit section *** (Lead.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Lead.Name Set end)

                // *** End programmer edit section *** (Lead.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LeadE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LeadE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LeadE", typeof(IIS.CRM.Lead));
                }
            }
            
            /// <summary>
            /// "LeadL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LeadL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LeadL", typeof(IIS.CRM.Lead));
                }
            }
        }
    }
}
