//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Lead.
    /// </summary>
    // *** Start programmer edit section *** (Lead CustomAttributes)

    // *** End programmer edit section *** (Lead CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LeadE", new string[] {
            "LeadOrNot as \'Lead or not\'",
            "Telephone as \'Telephone\'",
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Address as \'Address\'",
            "CompanyName as \'Company name\'",
            "Gender as \'Gender\'",
            "Email as \'Email\'",
            "Date as \'Date\'"})]
    [View("LeadL", new string[] {
            "LeadOrNot as \'Lead or not\'",
            "Telephone as \'Telephone\'",
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Address as \'Address\'",
            "CompanyName as \'Company name\'",
            "Gender as \'Gender\'",
            "Email as \'Email\'",
            "Date as \'Date\'"})]
    public class Lead : IIS.CRM.Contact
    {
        
        private IIS.CRM.tLead fLeadOrNot;
        
        // *** Start programmer edit section *** (Lead CustomMembers)

        // *** End programmer edit section *** (Lead CustomMembers)

        
        /// <summary>
        /// LeadOrNot.
        /// </summary>
        // *** Start programmer edit section *** (Lead.LeadOrNot CustomAttributes)

        // *** End programmer edit section *** (Lead.LeadOrNot CustomAttributes)
        public virtual IIS.CRM.tLead LeadOrNot
        {
            get
            {
                // *** Start programmer edit section *** (Lead.LeadOrNot Get start)

                // *** End programmer edit section *** (Lead.LeadOrNot Get start)
                IIS.CRM.tLead result = this.fLeadOrNot;
                // *** Start programmer edit section *** (Lead.LeadOrNot Get end)

                // *** End programmer edit section *** (Lead.LeadOrNot Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lead.LeadOrNot Set start)

                // *** End programmer edit section *** (Lead.LeadOrNot Set start)
                this.fLeadOrNot = value;
                // *** Start programmer edit section *** (Lead.LeadOrNot Set end)

                // *** End programmer edit section *** (Lead.LeadOrNot Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LeadE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LeadE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LeadE", typeof(IIS.CRM.Lead));
                }
            }
            
            /// <summary>
            /// "LeadL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LeadL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LeadL", typeof(IIS.CRM.Lead));
                }
            }
        }
    }
}
