//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T activity.
    /// </summary>
    // *** Start programmer edit section *** (tActivity CustomAttributes)

    // *** End programmer edit section *** (tActivity CustomAttributes)
    public enum tActivity
    {
        
        // *** Start programmer edit section *** (tActivity.Sales CustomAttributes)

        // *** End programmer edit section *** (tActivity.Sales CustomAttributes)
        [Caption("Sales")]
        Sales,
        
        // *** Start programmer edit section *** (tActivity.Interview CustomAttributes)

        // *** End programmer edit section *** (tActivity.Interview CustomAttributes)
        [Caption("Interview")]
        Interview,
        
        // *** Start programmer edit section *** (tActivity.Emaling CustomAttributes)

        // *** End programmer edit section *** (tActivity.Emaling CustomAttributes)
        [Caption("Emailing")]
        Emaling,
        
        // *** Start programmer edit section *** (tActivity.Reporting CustomAttributes)

        // *** End programmer edit section *** (tActivity.Reporting CustomAttributes)
        [Caption("Reporting")]
        Reporting,
        
        // *** Start programmer edit section *** (tActivity.Calling CustomAttributes)

        // *** End programmer edit section *** (tActivity.Calling CustomAttributes)
        [Caption("Calling")]
        Calling,
        
        // *** Start programmer edit section *** (tActivity.Meeting CustomAttributes)

        // *** End programmer edit section *** (tActivity.Meeting CustomAttributes)
        [Caption("Meeting")]
        Meeting,
        
        // *** Start programmer edit section *** (tActivity.Validating CustomAttributes)

        // *** End programmer edit section *** (tActivity.Validating CustomAttributes)
        [Caption("Validate customer")]
        Validating,
    }
}
