//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CRM
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T lead.
    /// </summary>
    // *** Start programmer edit section *** (tLead CustomAttributes)

    // *** End programmer edit section *** (tLead CustomAttributes)
    public enum tLead
    {
        
        // *** Start programmer edit section *** (tLead.Yes CustomAttributes)

        // *** End programmer edit section *** (tLead.Yes CustomAttributes)
        Yes,
        
        // *** Start programmer edit section *** (tLead.No CustomAttributes)

        // *** End programmer edit section *** (tLead.No CustomAttributes)
        No,
    }
}
