




CREATE TABLE Employer (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 EmployerRole VARCHAR(255) NULL,
 Administrator_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Lead (
 primaryKey UUID NOT NULL,
 LeadOrNot VARCHAR(4) NULL,
 Telephone VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Surname VARCHAR(255) NULL,
 Address VARCHAR(255) NULL,
 CompanyName VARCHAR(255) NULL,
 Gender VARCHAR(6) NULL,
 Email VARCHAR(255) NULL,
 Date TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Contact (
 primaryKey UUID NOT NULL,
 Telephone VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Surname VARCHAR(255) NULL,
 Address VARCHAR(255) NULL,
 CompanyName VARCHAR(255) NULL,
 Gender VARCHAR(6) NULL,
 Email VARCHAR(255) NULL,
 Date TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Administrator (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 Role VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Activity (
 primaryKey UUID NOT NULL,
 ActivityName VARCHAR(255) NULL,
 ActivityType VARCHAR(17) NULL,
 StartOfActivity TIMESTAMP(3) NULL,
 EndOfActivity TIMESTAMP(3) NULL,
 Contact_m0 UUID NULL,
 Contact_m1 UUID NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Employer ADD CONSTRAINT FKc1d9c18136491163d2c6d4096d4b405ced3246a2 FOREIGN KEY (Administrator_m0) REFERENCES Administrator; 
CREATE INDEX Indexc1d9c18136491163d2c6d4096d4b405ced3246a2 on Employer (Administrator_m0); 

 ALTER TABLE Activity ADD CONSTRAINT FK4dbf21e1a74cd910289467f94d9f8f2b74cdbfb2 FOREIGN KEY (Contact_m0) REFERENCES Contact; 
CREATE INDEX Index4dbf21e1a74cd910289467f94d9f8f2b74cdbfb2 on Activity (Contact_m0); 

 ALTER TABLE Activity ADD CONSTRAINT FKd3a6d412a385858b57cff1a0735e976510ba659c FOREIGN KEY (Contact_m1) REFERENCES Lead; 
CREATE INDEX Indexd3a6d412a385858b57cff1a0735e976510ba659c on Activity (Contact_m1); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

